### ISSUE TITLE
配置阿里云仓库时，引ci的包会报找不到

### ISSUE THREAD

**Issue by foxdd** [bkdevops-projects/devops-framework#106]
需要配置artifacturl，否则引入ci包时，会报关联的二级依赖找不到

**Comment by stubenhuang** [comment]
版本>=0.0.5-SNAPSHOT , 使用`-DmavenRepoUrl="xxx"` 可以加入自定义库 , 具体可以参考这篇文章
[Maven仓库](https://bkdevops-projects.github.io/devops-framework/#/dependency/repository)
