### ISSUE TITLE
【服务治理】客户端负载均衡&服务间灰度调用能力

### ISSUE THREAD

**Issue by carrypann** [bkdevops-projects/devops-framework#62]
SpringCloud 2020.0移除了对Ribbon的依赖，官方实现了客户端负载均衡组件`spring-cloud-starter-loadbalancer`，引入该组件以实现客户端的负载均衡，同时研究其扩展能力，微服务间调用支持按照metadata进行灰度调用

ref: [spring-cloud-loadbalancer docs](https://docs.spring.io/spring-cloud-commons/docs/3.0.2/reference/html/#spring-cloud-loadbalancer)

**Comment by stubenhuang** [comment]
服务发现需要同时兼容consul和k8s dns , 方便后续的容器化部署

**Comment by carrypann** [comment]
> 服务发现需要同时兼容consul和k8s dns , 方便后续的容器化部署

[#60](https://github.com/bkdevops-projects/devops-framework/issues/60)这个issue讨论了k8s云原生的打包方式
